const pets = [
  {
    id: 0,
    species: "alien",
    eating_habit: "carnivore",
    pet_name: "Xenomorph",
    image: "Xenomorph.jpg",
  },
  {
    id: 1,
    species: "dog",
    eating_habit: "omnivore",
    pet_name: "Brownie",
    image: "Brownie.jpg",
  },
  {
    id: 2,
    species: "cat",
    eating_habit: "carnivore",
    pet_name: "Oreo",
    image: "Oreo.jpg",
  },
  {
    id: 3,
    species: "rabbit",
    eating_habit: "herbivore",
    pet_name: "Snowball",
    image: "Snowball.jpg",
  },
  {
    id: 4,
    species: "parrot",
    eating_habit: "omnivore",
    pet_name: "Sunny",
    image: "Sunny.jpg",
  },
  {
    id: 5,
    species: "dog",
    eating_habit: "omnivore",
    pet_name: "Max",
    image: "Max.jpg",
  },
  {
    id: 6,
    species: "cat",
    eating_habit: "carnivore",
    pet_name: "Whiskers",
    image: "Whiskers.jpg",
  },
  {
    id: 7,
    species: "rabbit",
    eating_habit: "herbivore",
    pet_name: "Cottontail",
    image: "Cottontail.jpg",
  },
  {
    id: 8,
    species: "parrot",
    eating_habit: "omnivore",
    pet_name: "Polly",
    image: "Polly.jpg",
  },
  {
    id: 9,
    species: "dog",
    eating_habit: "omnivore",
    pet_name: "Rocky",
    image: "Rocky.jpg",
  },
  {
    id: 10,
    species: "cat",
    eating_habit: "carnivore",
    pet_name: "Mittens",
    image: "Mittens.jpg",
  },
];

module.exports = { pets };
